import { ColorFamilyType } from "@/types/shop";

type CategoryType = {
  label: string;
  slug: string;
};

export const ALL_CATEGORIES: CategoryType[] = [
  { label: "Smart Watches", slug: "smart-watches" },
  { label: "Audio Gear", slug: "audio-gear" },
  { label: "Power Banks", slug: "power-banks" },
  { label: "Smart Home", slug: "smart-home" },
  { label: "Peripherals", slug: "peripherals" },
  { label: "Mobile Accessories", slug: "mobile-accessories" },
  { label: "Laptops", slug: "laptops" },
  { label: "Tablets", slug: "tablets" },
  { label: "Smartphones", slug: "smartphones" },
  { label: "Headphones", slug: "headphones" },
  { label: "Earbuds", slug: "earbuds" },
  { label: "Speakers", slug: "speakers" },
  { label: "Keyboards", slug: "keyboards" },
  { label: "Mice", slug: "mice" },
  { label: "Monitors", slug: "monitors" },
  { label: "Webcams", slug: "webcams" },
  { label: "Microphones", slug: "microphones" },
  { label: "USB Hubs", slug: "usb-hubs" },
  { label: "Charging Cables", slug: "charging-cables" },
  { label: "Wireless Chargers", slug: "wireless-chargers" },
  { label: "Phone Cases", slug: "phone-cases" },
  { label: "Screen Protectors", slug: "screen-protectors" },
  { label: "Camera Lenses", slug: "camera-lenses" },
  { label: "Action Cameras", slug: "action-cameras" },
  { label: "Drones", slug: "drones" },
  { label: "VR Headsets", slug: "vr-headsets" },
  { label: "Gaming Controllers", slug: "gaming-controllers" },
  { label: "Gaming Headsets", slug: "gaming-headsets" },
  { label: "Gaming Chairs", slug: "gaming-chairs" },
  { label: "Gaming Desks", slug: "gaming-desks" },
  { label: "Desk Lamps", slug: "desk-lamps" },
  { label: "Monitor Stands", slug: "monitor-stands" },
  { label: "Laptop Stands", slug: "laptop-stands" },
  { label: "Laptop Bags", slug: "laptop-bags" },
  { label: "Backpacks", slug: "backpacks" },
  { label: "Cable Management", slug: "cable-management" },
  { label: "Smart Plugs", slug: "smart-plugs" },
  { label: "Smart Bulbs", slug: "smart-bulbs" },
  { label: "Smart Locks", slug: "smart-locks" },
  { label: "Smart Doorbells", slug: "smart-doorbells" },
  { label: "Security Cameras", slug: "security-cameras" },
  { label: "Baby Monitors", slug: "baby-monitors" },
  { label: "Robot Vacuums", slug: "robot-vacuums" },
  { label: "Air Purifiers", slug: "air-purifiers" },
  { label: "Humidifiers", slug: "humidifiers" },
  { label: "Electric Fans", slug: "electric-fans" },
  { label: "Portable Projectors", slug: "portable-projectors" },
  { label: "HDMI Cables", slug: "hdmi-cables" },
  { label: "Streaming Devices", slug: "streaming-devices" },
  { label: "Smart TVs", slug: "smart-tvs" },
  { label: "Remote Controls", slug: "remote-controls" },
  { label: "Printers", slug: "printers" },
  { label: "Scanners", slug: "scanners" },
  { label: "External Hard Drives", slug: "external-hard-drives" },
  { label: "SSDs", slug: "ssds" },
  { label: "Flash Drives", slug: "flash-drives" },
  { label: "Memory Cards", slug: "memory-cards" },
  { label: "Card Readers", slug: "card-readers" },
  { label: "Network Switches", slug: "network-switches" },
  { label: "Routers", slug: "routers" },
  { label: "Range Extenders", slug: "range-extenders" },
  { label: "Ethernet Cables", slug: "ethernet-cables" },
  { label: "Surge Protectors", slug: "surge-protectors" },
  { label: "UPS Systems", slug: "ups-systems" },
  { label: "Solar Chargers", slug: "solar-chargers" },
  { label: "Car Chargers", slug: "car-chargers" },
  { label: "Car Mounts", slug: "car-mounts" },
  { label: "Dash Cameras", slug: "dash-cameras" },
  { label: "GPS Trackers", slug: "gps-trackers" },
  { label: "Fitness Trackers", slug: "fitness-trackers" },
  { label: "Smart Rings", slug: "smart-rings" },
  { label: "Smart Glasses", slug: "smart-glasses" },
  { label: "Bluetooth Adapters", slug: "bluetooth-adapters" },
  { label: "Stylus Pens", slug: "stylus-pens" },
  { label: "Drawing Tablets", slug: "drawing-tablets" },
  { label: "Capture Cards", slug: "capture-cards" },
  { label: "Green Screens", slug: "green-screens" },
  { label: "Ring Lights", slug: "ring-lights" },
  { label: "Tripods", slug: "tripods" },
  { label: "Gimbal Stabilizers", slug: "gimbal-stabilizers" },
  { label: "Portable SSDs", slug: "portable-ssds" },
  { label: "NAS Devices", slug: "nas-devices" },
  { label: "Mini PCs", slug: "mini-pcs" },
  { label: "Raspberry Pi", slug: "raspberry-pi" },
  { label: "Arduino Kits", slug: "arduino-kits" },
  { label: "3D Printers", slug: "3d-printers" },
  { label: "Label Makers", slug: "label-makers" },
  { label: "Barcode Scanners", slug: "barcode-scanners" },
  { label: "POS Systems", slug: "pos-systems" },
  { label: "Receipt Printers", slug: "receipt-printers" },
  { label: "Thermal Printers", slug: "thermal-printers" },
  { label: "Smart Notebooks", slug: "smart-notebooks" },
  { label: "E-Readers", slug: "e-readers" },
  { label: "Portable Monitors", slug: "portable-monitors" },
  { label: "KVM Switches", slug: "kvm-switches" },
  { label: "Docking Stations", slug: "docking-stations" },
  { label: "Thunderbolt Hubs", slug: "thunderbolt-hubs" },
  { label: "Cooling Pads", slug: "cooling-pads" },
  { label: "Wrist Rests", slug: "wrist-rests" },
];


type BrandType = {
  label: string;
  value: string;
};

export const BRANDS: BrandType[] = [
  { label: "Apple", value: "apple" },
  { label: "Samsung", value: "samsung" },
  { label: "Sony", value: "sony" },
  { label: "LG", value: "lg" },
  { label: "Dell", value: "dell" },
  { label: "HP", value: "hp" },
  { label: "Lenovo", value: "lenovo" },
  { label: "Asus", value: "asus" },
  { label: "Acer", value: "acer" },
  { label: "Microsoft", value: "microsoft" },
  { label: "Google", value: "google" },
  { label: "Huawei", value: "huawei" },
  { label: "Xiaomi", value: "xiaomi" },
  { label: "OnePlus", value: "oneplus" },
  { label: "Oppo", value: "oppo" },
  { label: "Vivo", value: "vivo" },
  { label: "Realme", value: "realme" },
  { label: "Nokia", value: "nokia" },
  { label: "Motorola", value: "motorola" },
  { label: "Logitech", value: "logitech" },
  { label: "Razer", value: "razer" },
  { label: "Corsair", value: "corsair" },
  { label: "SteelSeries", value: "steelseries" },
  { label: "HyperX", value: "hyperx" },
  { label: "JBL", value: "jbl" },
  { label: "Bose", value: "bose" },
  { label: "Sennheiser", value: "sennheiser" },
  { label: "Audio-Technica", value: "audio-technica" },
  { label: "Anker", value: "anker" },
  { label: "Belkin", value: "belkin" },
  { label: "Philips", value: "philips" },
  { label: "Panasonic", value: "panasonic" },
  { label: "Toshiba", value: "toshiba" },
  { label: "Western Digital", value: "western-digital" },
  { label: "Seagate", value: "seagate" },
  { label: "Kingston", value: "kingston" },
  { label: "SanDisk", value: "sandisk" },
  { label: "TP-Link", value: "tp-link" },
  { label: "Netgear", value: "netgear" },
  { label: "DJI", value: "dji" },
];

type ShippingLocationtype = {
  label: string;
  value: string;
};

export const SHIPPING_LOCATIONS: ShippingLocationtype[] = [
  { label: "Dhaka", value: "dhaka" },
  { label: "Chittagong", value: "chittagong" },
  { label: "Rajshahi", value: "rajshahi" },
  { label: "Khulna", value: "khulna" },
  { label: "Sylhet", value: "sylhet" },
  { label: "Barishal", value: "barishal" },
  { label: "Mymensingh", value: "mymensingh" },
  { label: "Rangpur", value: "rangpur" },
];



export const COLOR_FAMILIES: ColorFamilyType[] = [
  { label: "Black", value: "black", hex: "#000000" },
  { label: "White", value: "white", hex: "#FFFFFF" },
  { label: "Red", value: "red", hex: "#EF4444" },
  { label: "Blue", value: "blue", hex: "#3B82F6" },
  { label: "Green", value: "green", hex: "#22C55E" },
  { label: "Yellow", value: "yellow", hex: "#EAB308" },
  { label: "Orange", value: "orange", hex: "#F97316" },
  { label: "Purple", value: "purple", hex: "#A855F7" },
  { label: "Pink", value: "pink", hex: "#EC4899" },
  { label: "Gray", value: "gray", hex: "#6B7280" },
  { label: "Brown", value: "brown", hex: "#92400E" },
  { label: "Navy", value: "navy", hex: "#1E3A5F" },
  { label: "Teal", value: "teal", hex: "#14B8A6" },
  { label: "Gold", value: "gold", hex: "#F59E0B" },
  { label: "Silver", value: "silver", hex: "#CBD5E1" },
  { label: "Cyan", value: "cyan", hex: "#06B6D4" },
  { label: "Lime", value: "lime", hex: "#84CC16" },
  { label: "Indigo", value: "indigo", hex: "#6366F1" },
  { label: "Violet", value: "violet", hex: "#7C3AED" },
  { label: "Rose", value: "rose", hex: "#F43F5E" },
  { label: "Amber", value: "amber", hex: "#D97706" },
  { label: "Emerald", value: "emerald", hex: "#10B981" },
  { label: "Sky", value: "sky", hex: "#0EA5E9" },
  { label: "Slate", value: "slate", hex: "#475569" },
  { label: "Zinc", value: "zinc", hex: "#71717A" },
  { label: "Stone", value: "stone", hex: "#78716C" },
  { label: "Coral", value: "coral", hex: "#FF6B6B" },
  { label: "Mint", value: "mint", hex: "#98FFB3" },
  { label: "Lavender", value: "lavender", hex: "#C4B5FD" },
  { label: "Peach", value: "peach", hex: "#FFCBA4" },
  { label: "Cream", value: "cream", hex: "#FFFDD0" },
  { label: "Maroon", value: "maroon", hex: "#800000" },
  { label: "Olive", value: "olive", hex: "#808000" },
  { label: "Turquoise", value: "turquoise", hex: "#40E0D0" },
  { label: "Magenta", value: "magenta", hex: "#FF00FF" },

];