import { BadgeType } from "@/types/product";
import { ColorFamilyType, ShopProductType } from "@/types/shop";

type CategoryType = {
  label: string;
  slug: string;
};

export const ALL_CATEGORIES: CategoryType[] = [
  { label: "Smart Watches", slug: "smart-watches" },
  { label: "Audio Gear", slug: "audio-gear" },
  { label: "Power Banks", slug: "power-banks" },
  { label: "Smart Home", slug: "smart-home" },
  { label: "Peripherals", slug: "peripherals" },
  { label: "Mobile Accessories", slug: "mobile-accessories" },
  { label: "Laptops", slug: "laptops" },
  { label: "Tablets", slug: "tablets" },
  { label: "Smartphones", slug: "smartphones" },
  { label: "Headphones", slug: "headphones" },
  { label: "Earbuds", slug: "earbuds" },
  { label: "Speakers", slug: "speakers" },
  { label: "Keyboards", slug: "keyboards" },
  { label: "Mice", slug: "mice" },
  { label: "Monitors", slug: "monitors" },
  { label: "Webcams", slug: "webcams" },
  { label: "Microphones", slug: "microphones" },
  { label: "USB Hubs", slug: "usb-hubs" },
  { label: "Charging Cables", slug: "charging-cables" },
  { label: "Wireless Chargers", slug: "wireless-chargers" },
  { label: "Phone Cases", slug: "phone-cases" },
  { label: "Screen Protectors", slug: "screen-protectors" },
  { label: "Camera Lenses", slug: "camera-lenses" },
  { label: "Action Cameras", slug: "action-cameras" },
  { label: "Drones", slug: "drones" },
  { label: "VR Headsets", slug: "vr-headsets" },
  { label: "Gaming Controllers", slug: "gaming-controllers" },
  { label: "Gaming Headsets", slug: "gaming-headsets" },
  { label: "Gaming Chairs", slug: "gaming-chairs" },
  { label: "Gaming Desks", slug: "gaming-desks" },
  { label: "Desk Lamps", slug: "desk-lamps" },
  { label: "Monitor Stands", slug: "monitor-stands" },
  { label: "Laptop Stands", slug: "laptop-stands" },
  { label: "Laptop Bags", slug: "laptop-bags" },
  { label: "Backpacks", slug: "backpacks" },
  { label: "Cable Management", slug: "cable-management" },
  { label: "Smart Plugs", slug: "smart-plugs" },
  { label: "Smart Bulbs", slug: "smart-bulbs" },
  { label: "Smart Locks", slug: "smart-locks" },
  { label: "Smart Doorbells", slug: "smart-doorbells" },
  { label: "Security Cameras", slug: "security-cameras" },
  { label: "Baby Monitors", slug: "baby-monitors" },
  { label: "Robot Vacuums", slug: "robot-vacuums" },
  { label: "Air Purifiers", slug: "air-purifiers" },
  { label: "Humidifiers", slug: "humidifiers" },
  { label: "Electric Fans", slug: "electric-fans" },
  { label: "Portable Projectors", slug: "portable-projectors" },
  { label: "HDMI Cables", slug: "hdmi-cables" },
  { label: "Streaming Devices", slug: "streaming-devices" },
  { label: "Smart TVs", slug: "smart-tvs" },
  { label: "Remote Controls", slug: "remote-controls" },
  { label: "Printers", slug: "printers" },
  { label: "Scanners", slug: "scanners" },
  { label: "External Hard Drives", slug: "external-hard-drives" },
  { label: "SSDs", slug: "ssds" },
  { label: "Flash Drives", slug: "flash-drives" },
  { label: "Memory Cards", slug: "memory-cards" },
  { label: "Card Readers", slug: "card-readers" },
  { label: "Network Switches", slug: "network-switches" },
  { label: "Routers", slug: "routers" },
  { label: "Range Extenders", slug: "range-extenders" },
  { label: "Ethernet Cables", slug: "ethernet-cables" },
  { label: "Surge Protectors", slug: "surge-protectors" },
  { label: "UPS Systems", slug: "ups-systems" },
  { label: "Solar Chargers", slug: "solar-chargers" },
  { label: "Car Chargers", slug: "car-chargers" },
  { label: "Car Mounts", slug: "car-mounts" },
  { label: "Dash Cameras", slug: "dash-cameras" },
  { label: "GPS Trackers", slug: "gps-trackers" },
  { label: "Fitness Trackers", slug: "fitness-trackers" },
  { label: "Smart Rings", slug: "smart-rings" },
  { label: "Smart Glasses", slug: "smart-glasses" },
  { label: "Bluetooth Adapters", slug: "bluetooth-adapters" },
  { label: "Stylus Pens", slug: "stylus-pens" },
  { label: "Drawing Tablets", slug: "drawing-tablets" },
  { label: "Capture Cards", slug: "capture-cards" },
  { label: "Green Screens", slug: "green-screens" },
  { label: "Ring Lights", slug: "ring-lights" },
  { label: "Tripods", slug: "tripods" },
  { label: "Gimbal Stabilizers", slug: "gimbal-stabilizers" },
  { label: "Portable SSDs", slug: "portable-ssds" },
  { label: "NAS Devices", slug: "nas-devices" },
  { label: "Mini PCs", slug: "mini-pcs" },
  { label: "Raspberry Pi", slug: "raspberry-pi" },
  { label: "Arduino Kits", slug: "arduino-kits" },
  { label: "3D Printers", slug: "3d-printers" },
  { label: "Label Makers", slug: "label-makers" },
  { label: "Barcode Scanners", slug: "barcode-scanners" },
  { label: "POS Systems", slug: "pos-systems" },
  { label: "Receipt Printers", slug: "receipt-printers" },
  { label: "Thermal Printers", slug: "thermal-printers" },
  { label: "Smart Notebooks", slug: "smart-notebooks" },
  { label: "E-Readers", slug: "e-readers" },
  { label: "Portable Monitors", slug: "portable-monitors" },
  { label: "KVM Switches", slug: "kvm-switches" },
  { label: "Docking Stations", slug: "docking-stations" },
  { label: "Thunderbolt Hubs", slug: "thunderbolt-hubs" },
  { label: "Cooling Pads", slug: "cooling-pads" },
  { label: "Wrist Rests", slug: "wrist-rests" },
];


type BrandType = {
  label: string;
  value: string;
};

export const BRANDS: BrandType[] = [
  { label: "Apple", value: "apple" },
  { label: "Samsung", value: "samsung" },
  { label: "Sony", value: "sony" },
  { label: "LG", value: "lg" },
  { label: "Dell", value: "dell" },
  { label: "HP", value: "hp" },
  { label: "Lenovo", value: "lenovo" },
  { label: "Asus", value: "asus" },
  { label: "Acer", value: "acer" },
  { label: "Microsoft", value: "microsoft" },
  { label: "Google", value: "google" },
  { label: "Huawei", value: "huawei" },
  { label: "Xiaomi", value: "xiaomi" },
  { label: "OnePlus", value: "oneplus" },
  { label: "Oppo", value: "oppo" },
  { label: "Vivo", value: "vivo" },
  { label: "Realme", value: "realme" },
  { label: "Nokia", value: "nokia" },
  { label: "Motorola", value: "motorola" },
  { label: "Logitech", value: "logitech" },
  { label: "Razer", value: "razer" },
  { label: "Corsair", value: "corsair" },
  { label: "SteelSeries", value: "steelseries" },
  { label: "HyperX", value: "hyperx" },
  { label: "JBL", value: "jbl" },
  { label: "Bose", value: "bose" },
  { label: "Sennheiser", value: "sennheiser" },
  { label: "Audio-Technica", value: "audio-technica" },
  { label: "Anker", value: "anker" },
  { label: "Belkin", value: "belkin" },
  { label: "Philips", value: "philips" },
  { label: "Panasonic", value: "panasonic" },
  { label: "Toshiba", value: "toshiba" },
  { label: "Western Digital", value: "western-digital" },
  { label: "Seagate", value: "seagate" },
  { label: "Kingston", value: "kingston" },
  { label: "SanDisk", value: "sandisk" },
  { label: "TP-Link", value: "tp-link" },
  { label: "Netgear", value: "netgear" },
  { label: "DJI", value: "dji" },
];

type ShippingLocationtype = {
  label: string;
  value: string;
};

export const SHIPPING_LOCATIONS: ShippingLocationtype[] = [
  { label: "Dhaka", value: "dhaka" },
  { label: "Chittagong", value: "chittagong" },
  { label: "Rajshahi", value: "rajshahi" },
  { label: "Khulna", value: "khulna" },
  { label: "Sylhet", value: "sylhet" },
  { label: "Barishal", value: "barishal" },
  { label: "Mymensingh", value: "mymensingh" },
  { label: "Rangpur", value: "rangpur" },
];



export const COLOR_FAMILIES: ColorFamilyType[] = [
  { label: "Black", value: "black", hex: "#000000" },
  { label: "White", value: "white", hex: "#FFFFFF" },
  { label: "Red", value: "red", hex: "#EF4444" },
  { label: "Blue", value: "blue", hex: "#3B82F6" },
  { label: "Green", value: "green", hex: "#22C55E" },
  { label: "Yellow", value: "yellow", hex: "#EAB308" },
  { label: "Orange", value: "orange", hex: "#F97316" },
  { label: "Purple", value: "purple", hex: "#A855F7" },
  { label: "Pink", value: "pink", hex: "#EC4899" },
  { label: "Gray", value: "gray", hex: "#6B7280" },
  { label: "Brown", value: "brown", hex: "#92400E" },
  { label: "Navy", value: "navy", hex: "#1E3A5F" },
  { label: "Teal", value: "teal", hex: "#14B8A6" },
  { label: "Gold", value: "gold", hex: "#F59E0B" },
  { label: "Silver", value: "silver", hex: "#CBD5E1" },
  { label: "Cyan", value: "cyan", hex: "#06B6D4" },
  { label: "Lime", value: "lime", hex: "#84CC16" },
  { label: "Indigo", value: "indigo", hex: "#6366F1" },
  { label: "Violet", value: "violet", hex: "#7C3AED" },
  { label: "Rose", value: "rose", hex: "#F43F5E" },
  { label: "Amber", value: "amber", hex: "#D97706" },
  { label: "Emerald", value: "emerald", hex: "#10B981" },
  { label: "Sky", value: "sky", hex: "#0EA5E9" },
  { label: "Slate", value: "slate", hex: "#475569" },
  { label: "Zinc", value: "zinc", hex: "#71717A" },
  { label: "Stone", value: "stone", hex: "#78716C" },
  { label: "Coral", value: "coral", hex: "#FF6B6B" },
  { label: "Mint", value: "mint", hex: "#98FFB3" },
  { label: "Lavender", value: "lavender", hex: "#C4B5FD" },
  { label: "Peach", value: "peach", hex: "#FFCBA4" },
  { label: "Cream", value: "cream", hex: "#FFFDD0" },
  { label: "Maroon", value: "maroon", hex: "#800000" },
  { label: "Olive", value: "olive", hex: "#808000" },
  { label: "Turquoise", value: "turquoise", hex: "#40E0D0" },
  { label: "Magenta", value: "magenta", hex: "#FF00FF" },

];




export const SHOP_PRODUCTS: ShopProductType[] = [
  { id: 1, title: "Ultra Retina X-1 Tablet", brand: "Apple", image: "/products/fs_1.png", regular_price: 999, discount: 25, badge: "SALE", rating: 4.8, category: "tablets", color: "silver", shipped_from: "dhaka" },
  { id: 2, title: "Pure Sound ANC Headphones", brand: "Sony", image: "/products/fs_2.png", regular_price: 399, discount: 25, badge: "HOT", rating: 4.6, category: "headphones", color: "black", shipped_from: "chittagong" },
  { id: 3, title: "Active Pro Series 5 Watch", brand: "Samsung", image: "/products/fs_3.png", regular_price: 240, discount: 21, badge: null, rating: 4.4, category: "smart-watches", color: "black", shipped_from: "dhaka" },
  { id: 4, title: "Titan 20K PD Power Bank", brand: "Anker", image: "/products/fs_4.png", regular_price: 79, discount: 38, badge: null, rating: 4.3, category: "power-banks", color: "white", shipped_from: "rajshahi" },
  { id: 5, title: "Nova RGB Mechanical Keyboard", brand: "Corsair", image: "/products/na_1.jpg", regular_price: 129, discount: 0, badge: "NEW", rating: 4.7, category: "keyboards", color: "black", shipped_from: "dhaka" },
  { id: 6, title: "Glide Precision Mouse", brand: "Logitech", image: "/products/na_2.jpg", regular_price: 59, discount: 0, badge: "NEW", rating: 4.5, category: "mice", color: "white", shipped_from: "dhaka" },
  { id: 7, title: "Lumina S24 Ultra", brand: "Samsung", image: "/products/na_3.jpg", regular_price: 1099, discount: 0, badge: "NEW", rating: 4.9, category: "smartphones", color: "navy", shipped_from: "chittagong" },
  { id: 8, title: "Aura Pods Elite", brand: "Apple", image: "/products/na_4.jpg", regular_price: 199, discount: 0, badge: "NEW", rating: 4.6, category: "earbuds", color: "white", shipped_from: "dhaka" },
  { id: 9, title: "Steel Desk Phone Stand", brand: "Belkin", image: "/products/na_5.jpg", regular_price: 35, discount: 0, badge: "NEW", rating: 4.2, category: "mobile-accessories", color: "silver", shipped_from: "sylhet" },
  { id: 10, title: "ProBook 15 Laptop", brand: "HP", image: "/products/p_10.jpg", regular_price: 1299, discount: 15, badge: "SALE", rating: 4.5, category: "laptops", color: "silver", shipped_from: "dhaka" },
  { id: 11, title: "ZenBook Pro 14", brand: "Asus", image: "/products/p_11.jpg", regular_price: 1499, discount: 10, badge: null, rating: 4.7, category: "laptops", color: "gray", shipped_from: "dhaka" },
  { id: 12, title: "IdeaPad Slim 5", brand: "Lenovo", image: "/products/p_12.jpg", regular_price: 899, discount: 20, badge: "SALE", rating: 4.3, category: "laptops", color: "blue", shipped_from: "rajshahi" },
  { id: 13, title: "Inspiron 15 3000", brand: "Dell", image: "/products/p_13.jpg", regular_price: 799, discount: 12, badge: null, rating: 4.2, category: "laptops", color: "black", shipped_from: "khulna" },
  { id: 14, title: "Surface Pro 9", brand: "Microsoft", image: "/products/p_14.jpg", regular_price: 1599, discount: 8, badge: null, rating: 4.8, category: "tablets", color: "silver", shipped_from: "dhaka" },
  { id: 15, title: "Galaxy Tab S9", brand: "Samsung", image: "/products/p_15.jpg", regular_price: 749, discount: 18, badge: "SALE", rating: 4.6, category: "tablets", color: "gray", shipped_from: "chittagong" },
  { id: 16, title: "iPad Air M2", brand: "Apple", image: "/products/p_16.jpg", regular_price: 899, discount: 5, badge: null, rating: 4.9, category: "tablets", color: "blue", shipped_from: "dhaka" },
  { id: 17, title: "Pixel 8 Pro", brand: "Google", image: "/products/p_17.jpg", regular_price: 999, discount: 15, badge: null, rating: 4.7, category: "smartphones", color: "black", shipped_from: "dhaka" },
  { id: 18, title: "iPhone 15 Pro", brand: "Apple", image: "/products/p_18.jpg", regular_price: 1199, discount: 0, badge: "NEW", rating: 4.9, category: "smartphones", color: "gold", shipped_from: "dhaka" },
  { id: 19, title: "OnePlus 12R", brand: "OnePlus", image: "/products/p_19.jpg", regular_price: 599, discount: 22, badge: "SALE", rating: 4.5, category: "smartphones", color: "green", shipped_from: "sylhet" },
  { id: 20, title: "Redmi Note 13 Pro", brand: "Xiaomi", image: "/products/p_20.jpg", regular_price: 299, discount: 30, badge: "SALE", rating: 4.3, category: "smartphones", color: "purple", shipped_from: "mymensingh" },
  { id: 21, title: "WH-1000XM5 Headphones", brand: "Sony", image: "/products/p_21.jpg", regular_price: 349, discount: 15, badge: null, rating: 4.8, category: "headphones", color: "black", shipped_from: "dhaka" },
  { id: 22, title: "QuietComfort 45", brand: "Bose", image: "/products/p_22.jpg", regular_price: 329, discount: 10, badge: null, rating: 4.7, category: "headphones", color: "white", shipped_from: "dhaka" },
  { id: 23, title: "HD 560S Open Back", brand: "Sennheiser", image: "/products/p_23.jpg", regular_price: 199, discount: 5, badge: null, rating: 4.6, category: "headphones", color: "black", shipped_from: "chittagong" },
  { id: 24, title: "ATH-M50xBT2", brand: "Audio-Technica", image: "/products/p_24.jpg", regular_price: 179, discount: 18, badge: "SALE", rating: 4.5, category: "headphones", color: "black", shipped_from: "rajshahi" },
  { id: 25, title: "Galaxy Buds Pro 2", brand: "Samsung", image: "/products/p_25.jpg", regular_price: 229, discount: 20, badge: "SALE", rating: 4.4, category: "earbuds", color: "white", shipped_from: "dhaka" },
  { id: 26, title: "FreeBuds Pro 3", brand: "Huawei", image: "/products/p_26.jpg", regular_price: 189, discount: 15, badge: null, rating: 4.3, category: "earbuds", color: "silver", shipped_from: "khulna" },
  { id: 27, title: "Soundcore Liberty 4", brand: "Anker", image: "/products/p_27.jpg", regular_price: 99, discount: 25, badge: "SALE", rating: 4.4, category: "earbuds", color: "navy", shipped_from: "barishal" },
  { id: 28, title: "Charge 5 Portable Speaker", brand: "JBL", image: "/products/p_28.jpg", regular_price: 179, discount: 12, badge: null, rating: 4.6, category: "speakers", color: "black", shipped_from: "dhaka" },
  { id: 29, title: "SoundLink Flex", brand: "Bose", image: "/products/p_29.jpg", regular_price: 149, discount: 8, badge: null, rating: 4.7, category: "speakers", color: "teal", shipped_from: "dhaka" },
  { id: 30, title: "Wonderboom 3", brand: "JBL", image: "/products/p_30.jpg", regular_price: 99, discount: 20, badge: "SALE", rating: 4.4, category: "speakers", color: "red", shipped_from: "sylhet" },
  { id: 31, title: "MX Keys Advanced Keyboard", brand: "Logitech", image: "/products/p_31.jpg", regular_price: 119, discount: 10, badge: null, rating: 4.7, category: "keyboards", color: "gray", shipped_from: "dhaka" },
  { id: 32, title: "BlackWidow V4 Pro", brand: "Razer", image: "/products/p_32.jpg", regular_price: 229, discount: 15, badge: null, rating: 4.6, category: "keyboards", color: "black", shipped_from: "dhaka" },
  { id: 33, title: "Apex Pro TKL", brand: "SteelSeries", image: "/products/p_33.jpg", regular_price: 199, discount: 20, badge: "SALE", rating: 4.8, category: "keyboards", color: "black", shipped_from: "chittagong" },
  { id: 34, title: "MX Master 3S Mouse", brand: "Logitech", image: "/products/p_34.jpg", regular_price: 99, discount: 5, badge: null, rating: 4.8, category: "mice", color: "black", shipped_from: "dhaka" },
  { id: 35, title: "DeathAdder V3 Pro", brand: "Razer", image: "/products/p_35.jpg", regular_price: 149, discount: 18, badge: null, rating: 4.7, category: "mice", color: "black", shipped_from: "dhaka" },
  { id: 36, title: "Rival 650 Wireless", brand: "SteelSeries", image: "/products/p_36.jpg", regular_price: 119, discount: 25, badge: "SALE", rating: 4.5, category: "mice", color: "black", shipped_from: "rajshahi" },
  { id: 37, title: "Cloud Alpha Wireless", brand: "HyperX", image: "/products/p_37.jpg", regular_price: 199, discount: 15, badge: null, rating: 4.7, category: "gaming-headsets", color: "red", shipped_from: "dhaka" },
  { id: 38, title: "Kraken V3 Pro", brand: "Razer", image: "/products/p_38.jpg", regular_price: 179, discount: 20, badge: null, rating: 4.5, category: "gaming-headsets", color: "black", shipped_from: "dhaka" },
  { id: 39, title: "Arctis Nova Pro", brand: "SteelSeries", image: "/products/p_39.jpg", regular_price: 349, discount: 10, badge: null, rating: 4.8, category: "gaming-headsets", color: "white", shipped_from: "chittagong" },
  { id: 40, title: "PowerCore 26800", brand: "Anker", image: "/products/p_40.jpg", regular_price: 59, discount: 30, badge: "SALE", rating: 4.5, category: "power-banks", color: "black", shipped_from: "dhaka" },
  { id: 41, title: "BatteryPack 20000", brand: "Belkin", image: "/products/p_41.jpg", regular_price: 69, discount: 20, badge: null, rating: 4.3, category: "power-banks", color: "white", shipped_from: "sylhet" },
  { id: 42, title: "Mi Power Bank 3 Pro", brand: "Xiaomi", image: "/products/p_42.jpg", regular_price: 45, discount: 35, badge: "SALE", rating: 4.4, category: "power-banks", color: "silver", shipped_from: "mymensingh" },
  { id: 43, title: "27\" 4K IPS Monitor", brand: "LG", image: "/products/p_43.jpg", regular_price: 599, discount: 15, badge: null, rating: 4.7, category: "monitors", color: "black", shipped_from: "dhaka" },
  { id: 44, title: "Odyssey G7 32\"", brand: "Samsung", image: "/products/p_44.jpg", regular_price: 799, discount: 20, badge: "SALE", rating: 4.8, category: "monitors", color: "black", shipped_from: "dhaka" },
  { id: 45, title: "ProArt PA279CV", brand: "Asus", image: "/products/p_45.jpg", regular_price: 499, discount: 10, badge: null, rating: 4.6, category: "monitors", color: "black", shipped_from: "chittagong" },
  { id: 46, title: "StreamCam Plus", brand: "Logitech", image: "/products/p_46.jpg", regular_price: 149, discount: 12, badge: null, rating: 4.5, category: "webcams", color: "white", shipped_from: "dhaka" },
  { id: 47, title: "Kiyo Pro Ultra", brand: "Razer", image: "/products/p_47.jpg", regular_price: 199, discount: 18, badge: null, rating: 4.6, category: "webcams", color: "black", shipped_from: "dhaka" },
  { id: 48, title: "Blue Yeti X", brand: "Logitech", image: "/products/p_48.jpg", regular_price: 169, discount: 15, badge: null, rating: 4.7, category: "microphones", color: "black", shipped_from: "dhaka" },
  { id: 49, title: "HyperX QuadCast S", brand: "HyperX", image: "/products/p_49.jpg", regular_price: 159, discount: 20, badge: "SALE", rating: 4.6, category: "microphones", color: "black", shipped_from: "rajshahi" },
  { id: 50, title: "Elgato Wave 3", brand: "Corsair", image: "/products/p_50.jpg", regular_price: 149, discount: 10, badge: null, rating: 4.5, category: "microphones", color: "black", shipped_from: "dhaka" },
  { id: 51, title: "Anker USB-C Hub 7-in-1", brand: "Anker", image: "/products/p_51.jpg", regular_price: 49, discount: 20, badge: null, rating: 4.5, category: "usb-hubs", color: "gray", shipped_from: "dhaka" },
  { id: 52, title: "CalDigit TS4 Dock", brand: "Belkin", image: "/products/p_52.jpg", regular_price: 349, discount: 8, badge: null, rating: 4.8, category: "docking-stations", color: "silver", shipped_from: "dhaka" },
  { id: 53, title: "Thunderbolt 4 Hub", brand: "Asus", image: "/products/p_53.jpg", regular_price: 199, discount: 12, badge: null, rating: 4.6, category: "thunderbolt-hubs", color: "black", shipped_from: "chittagong" },
  { id: 54, title: "Portable SSD T7", brand: "Samsung", image: "/products/p_54.jpg", regular_price: 129, discount: 25, badge: "SALE", rating: 4.8, category: "portable-ssds", color: "blue", shipped_from: "dhaka" },
  { id: 55, title: "My Passport 2TB", brand: "Western Digital", image: "/products/p_55.jpg", regular_price: 89, discount: 15, badge: null, rating: 4.5, category: "external-hard-drives", color: "black", shipped_from: "dhaka" },
  { id: 56, title: "Backup Plus 4TB", brand: "Seagate", image: "/products/p_56.jpg", regular_price: 109, discount: 20, badge: "SALE", rating: 4.4, category: "external-hard-drives", color: "black", shipped_from: "sylhet" },
  { id: 57, title: "DataTraveler 256GB", brand: "Kingston", image: "/products/p_57.jpg", regular_price: 29, discount: 30, badge: "SALE", rating: 4.3, category: "flash-drives", color: "black", shipped_from: "rangpur" },
  { id: 58, title: "Extreme Pro MicroSD", brand: "SanDisk", image: "/products/p_58.jpg", regular_price: 39, discount: 25, badge: null, rating: 4.6, category: "memory-cards", color: "red", shipped_from: "dhaka" },
  { id: 59, title: "Archer AX6000 Router", brand: "TP-Link", image: "/products/p_59.jpg", regular_price: 299, discount: 18, badge: null, rating: 4.6, category: "routers", color: "black", shipped_from: "dhaka" },
  { id: 60, title: "Nighthawk AX12", brand: "Netgear", image: "/products/p_60.jpg", regular_price: 449, discount: 15, badge: null, rating: 4.7, category: "routers", color: "black", shipped_from: "dhaka" },
  { id: 61, title: "Deco XE75 Mesh", brand: "TP-Link", image: "/products/p_61.jpg", regular_price: 249, discount: 20, badge: "SALE", rating: 4.5, category: "range-extenders", color: "white", shipped_from: "chittagong" },
  { id: 62, title: "Pad Pro Wireless Charger", brand: "Belkin", image: "/products/p_62.jpg", regular_price: 59, discount: 15, badge: null, rating: 4.4, category: "wireless-chargers", color: "white", shipped_from: "dhaka" },
  { id: 63, title: "MagSafe Charger 15W", brand: "Apple", image: "/products/p_63.jpg", regular_price: 39, discount: 0, badge: "NEW", rating: 4.6, category: "wireless-chargers", color: "white", shipped_from: "dhaka" },
  { id: 64, title: "65W GaN Car Charger", brand: "Anker", image: "/products/p_64.jpg", regular_price: 35, discount: 28, badge: "SALE", rating: 4.5, category: "car-chargers", color: "black", shipped_from: "rajshahi" },
  { id: 65, title: "Magnetic Car Mount Pro", brand: "Belkin", image: "/products/p_65.jpg", regular_price: 45, discount: 22, badge: null, rating: 4.3, category: "car-mounts", color: "black", shipped_from: "dhaka" },
  { id: 66, title: "Dash Cam 4K Pro", brand: "Xiaomi", image: "/products/p_66.jpg", regular_price: 89, discount: 30, badge: "SALE", rating: 4.4, category: "dash-cameras", color: "black", shipped_from: "khulna" },
  { id: 67, title: "Mini 4 Pro Drone", brand: "DJI", image: "/products/p_67.jpg", regular_price: 759, discount: 5, badge: null, rating: 4.9, category: "drones", color: "gray", shipped_from: "dhaka" },
  { id: 68, title: "Action Cam 11 Black", brand: "Sony", image: "/products/p_68.jpg", regular_price: 399, discount: 12, badge: null, rating: 4.7, category: "action-cameras", color: "black", shipped_from: "dhaka" },
  { id: 69, title: "Ring Light 18\"", brand: "Philips", image: "/products/p_69.jpg", regular_price: 79, discount: 35, badge: "SALE", rating: 4.4, category: "ring-lights", color: "white", shipped_from: "sylhet" },
  { id: 70, title: "Gorilla Tripod Flexible", brand: "Logitech", image: "/products/p_70.jpg", regular_price: 55, discount: 20, badge: null, rating: 4.3, category: "tripods", color: "black", shipped_from: "dhaka" },
  { id: 71, title: "Smart LED Bulb A19", brand: "Philips", image: "/products/p_71.jpg", regular_price: 19, discount: 15, badge: null, rating: 4.5, category: "smart-bulbs", color: "white", shipped_from: "dhaka" },
  { id: 72, title: "Smart Plug Mini", brand: "TP-Link", image: "/products/p_72.jpg", regular_price: 25, discount: 20, badge: null, rating: 4.6, category: "smart-plugs", color: "white", shipped_from: "dhaka" },
  { id: 73, title: "Video Doorbell Pro 2", brand: "Belkin", image: "/products/p_73.jpg", regular_price: 249, discount: 18, badge: null, rating: 4.5, category: "smart-doorbells", color: "black", shipped_from: "dhaka" },
  { id: 74, title: "Indoor Security Cam", brand: "TP-Link", image: "/products/p_74.jpg", regular_price: 49, discount: 30, badge: "SALE", rating: 4.4, category: "security-cameras", color: "white", shipped_from: "chittagong" },
  { id: 75, title: "Robot Vacuum S8 Pro", brand: "Xiaomi", image: "/products/p_75.jpg", regular_price: 599, discount: 22, badge: null, rating: 4.7, category: "robot-vacuums", color: "black", shipped_from: "dhaka" },
  { id: 76, title: "Air Purifier 400S", brand: "Philips", image: "/products/p_76.jpg", regular_price: 299, discount: 15, badge: null, rating: 4.6, category: "air-purifiers", color: "white", shipped_from: "dhaka" },
  { id: 77, title: "Portable Projector P3", brand: "Samsung", image: "/products/p_77.jpg", regular_price: 849, discount: 10, badge: null, rating: 4.7, category: "portable-projectors", color: "white", shipped_from: "dhaka" },
  { id: 78, title: "Fire TV Stick 4K Max", brand: "Amazon", image: "/products/p_78.jpg", regular_price: 59, discount: 25, badge: "SALE", rating: 4.6, category: "streaming-devices", color: "black", shipped_from: "dhaka" },
  { id: 79, title: "Chromecast 4K", brand: "Google", image: "/products/p_79.jpg", regular_price: 49, discount: 18, badge: null, rating: 4.5, category: "streaming-devices", color: "white", shipped_from: "sylhet" },
  { id: 80, title: "Wacom Intuos Pro M", brand: "Logitech", image: "/products/p_80.jpg", regular_price: 379, discount: 12, badge: null, rating: 4.7, category: "drawing-tablets", color: "black", shipped_from: "dhaka" },
  { id: 81, title: "iPad Pencil Pro", brand: "Apple", image: "/products/p_81.jpg", regular_price: 129, discount: 0, badge: "NEW", rating: 4.8, category: "stylus-pens", color: "white", shipped_from: "dhaka" },
  { id: 82, title: "Elgato HD60 X Capture", brand: "Corsair", image: "/products/p_82.jpg", regular_price: 149, discount: 15, badge: null, rating: 4.6, category: "capture-cards", color: "black", shipped_from: "dhaka" },
  { id: 83, title: "Cooling Pad N19", brand: "Asus", image: "/products/p_83.jpg", regular_price: 39, discount: 25, badge: null, rating: 4.3, category: "cooling-pads", color: "black", shipped_from: "rangpur" },
  { id: 84, title: "Laptop Stand Aluminum", brand: "Belkin", image: "/products/p_84.jpg", regular_price: 49, discount: 20, badge: null, rating: 4.5, category: "laptop-stands", color: "silver", shipped_from: "dhaka" },
  { id: 85, title: "Monitor Arm Single", brand: "Logitech", image: "/products/p_85.jpg", regular_price: 89, discount: 15, badge: null, rating: 4.6, category: "monitor-stands", color: "black", shipped_from: "dhaka" },
  { id: 86, title: "Ergonomic Wrist Rest", brand: "Corsair", image: "/products/p_86.jpg", regular_price: 29, discount: 10, badge: null, rating: 4.2, category: "wrist-rests", color: "black", shipped_from: "chittagong" },
  { id: 87, title: "55W GaN Charger", brand: "Anker", image: "/products/p_87.jpg", regular_price: 45, discount: 30, badge: "SALE", rating: 4.7, category: "charging-cables", color: "white", shipped_from: "dhaka" },
  { id: 88, title: "Cat8 Ethernet Cable 10m", brand: "TP-Link", image: "/products/p_88.jpg", regular_price: 25, discount: 20, badge: null, rating: 4.4, category: "ethernet-cables", color: "black", shipped_from: "barishal" },
  { id: 89, title: "8-Port Gigabit Switch", brand: "TP-Link", image: "/products/p_89.jpg", regular_price: 35, discount: 15, badge: null, rating: 4.5, category: "network-switches", color: "black", shipped_from: "dhaka" },
  { id: 90, title: "UPS 1500VA", brand: "Philips", image: "/products/p_90.jpg", regular_price: 199, discount: 12, badge: null, rating: 4.6, category: "ups-systems", color: "black", shipped_from: "dhaka" },
  { id: 91, title: "Surge Protector 6-Outlet", brand: "Belkin", image: "/products/p_91.jpg", regular_price: 39, discount: 18, badge: null, rating: 4.5, category: "surge-protectors", color: "white", shipped_from: "sylhet" },
  { id: 92, title: "E-Reader Paperwhite 11", brand: "Amazon", image: "/products/p_92.jpg", regular_price: 139, discount: 20, badge: "SALE", rating: 4.7, category: "e-readers", color: "black", shipped_from: "dhaka" },
  { id: 93, title: "Smart Notebook Rocketbook", brand: "Belkin", image: "/products/p_93.jpg", regular_price: 35, discount: 15, badge: null, rating: 4.3, category: "smart-notebooks", color: "navy", shipped_from: "mymensingh" },
  { id: 94, title: "GPS Tracker Mini", brand: "Xiaomi", image: "/products/p_94.jpg", regular_price: 29, discount: 35, badge: "SALE", rating: 4.2, category: "gps-trackers", color: "black", shipped_from: "dhaka" },
  { id: 95, title: "Fitness Band 7 Pro", brand: "Huawei", image: "/products/p_95.jpg", regular_price: 89, discount: 28, badge: "SALE", rating: 4.4, category: "fitness-trackers", color: "black", shipped_from: "chittagong" },
  { id: 96, title: "Smart Ring Oura Gen4", brand: "Samsung", image: "/products/p_96.jpg", regular_price: 299, discount: 0, badge: "NEW", rating: 4.6, category: "smart-rings", color: "gold", shipped_from: "dhaka" },
  { id: 97, title: "VR Headset Quest 3", brand: "Microsoft", image: "/products/p_97.jpg", regular_price: 499, discount: 10, badge: null, rating: 4.8, category: "vr-headsets", color: "white", shipped_from: "dhaka" },
  { id: 98, title: "Xbox Wireless Controller", brand: "Microsoft", image: "/products/p_98.jpg", regular_price: 59, discount: 15, badge: null, rating: 4.7, category: "gaming-controllers", color: "black", shipped_from: "dhaka" },
  { id: 99, title: "DualSense Edge Controller", brand: "Sony", image: "/products/p_99.jpg", regular_price: 199, discount: 8, badge: null, rating: 4.8, category: "gaming-controllers", color: "white", shipped_from: "chittagong" },
  { id: 100, title: "Portable Monitor 15.6\"", brand: "Asus", image: "/products/p_100.jpg", regular_price: 249, discount: 20, badge: "SALE", rating: 4.5, category: "portable-monitors", color: "silver", shipped_from: "dhaka" },
];

const RATING_COUNTS: Record<number, number> = {
  1: 2847, 2: 1923, 3: 3102, 4: 5641, 5: 892,
  6: 1204, 7: 4312, 8: 2108, 9: 743, 10: 1876,
  11: 2341, 12: 987, 13: 1654, 14: 3201, 15: 2789,
  16: 4102, 17: 1567, 18: 6234, 19: 2341, 20: 8901,
  21: 3456, 22: 2109, 23: 1234, 24: 987, 25: 3421,
  26: 876, 27: 2341, 28: 1987, 29: 2341, 30: 1654,
  31: 2987, 32: 1876, 33: 2341, 34: 4521, 35: 3102,
  36: 1234, 37: 2109, 38: 1876, 39: 987, 40: 5432,
  41: 1234, 42: 7654, 43: 2341, 44: 1987, 45: 1432,
  46: 1876, 47: 1234, 48: 3421, 49: 2109, 50: 1765,
  51: 4321, 52: 876, 53: 1234, 54: 3456, 55: 2987,
  56: 2341, 57: 6789, 58: 3214, 59: 1876, 60: 1432,
  61: 2109, 62: 3421, 63: 5678, 64: 4321, 65: 2341,
  66: 1987, 67: 3456, 68: 2109, 69: 4321, 70: 1876,
  71: 8765, 72: 6543, 73: 2341, 74: 4321, 75: 3210,
  76: 1987, 77: 1432, 78: 5678, 79: 4321, 80: 987,
  81: 3456, 82: 1234, 83: 2341, 84: 3210, 85: 1987,
  86: 4321, 87: 5678, 88: 3456, 89: 4321, 90: 2109,
  91: 3456, 92: 4321, 93: 1234, 94: 5678, 95: 3210,
  96: 2109, 97: 3456, 98: 6789, 99: 4321, 100: 2987,
};

export const SHOP_PRODUCTS_WITH_COUNTS = SHOP_PRODUCTS.map((p) => ({
  ...p,
  rating_count: RATING_COUNTS[p.id],
}));