import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "swiper/css";
import { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import { Suspense } from "react";
import { GlobalProvider } from "@/components";
import { TooltipProvider } from "@/components/ui/tooltip";
import SessionWrapperProvider from "@/providers/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Suspense>
          <SessionWrapperProvider>
            <GlobalProvider>
              <SkeletonTheme>
                <TooltipProvider>{children}</TooltipProvider>
              </SkeletonTheme>
            </GlobalProvider>
          </SessionWrapperProvider>
        </Suspense>
      </body>
    </html>
  );
}
